
CFLAGS=-g -I../include -I../str -I../strprintf

strvec.o: strvec.c strvec.h ../str/str.h ../str/str_inline.h ../str/str_io.h ../strprintf/str_printf.h ../str/str_type.h

debug_strvec.o: strvec.c strvec.h ../str/str.h

clean:
	rm -rf a.out *.o 
