
CFLAGS=-g -I../include -I../str -I../strvec -I../strprintf
LDFLAGS=-g
strsplit.o: strsplit.c strsplit.h ../strvec/strvec.h ../str/str.h ../str/str_inline.h ../str/str_io.h ../strprintf/str_printf.h ../str/str_type.h

clean:
	rm -f a.out *.o 
